Hello and welcome to this video on introduction to libraries and frameworks in Python. In this video, we will learn about some of the most popular and useful libraries and frameworks that can help us perform various tasks and create web applications with Python. We will cover the following topics:

- NumPy for numerical computing, which allows us to work with arrays and perform mathematical operations on them.
- Pandas for data manipulation, which allows us to work with tabular data and perform data cleaning and analysis tasks.
- Matplotlib for data visualization, which allows us to create plots and charts to display and explore data.
- FastAPI for web development, which allows us to create fast and modern web APIs with Python based on standard type hints.
- Django for web development, which allows us to create full-featured web applications with Python based on the MVC architecture.

By the end of this video, you will have a basic understanding of these libraries and frameworks and how to use them in your Python projects.

## NumPy for Numerical Computing

NumPy, which stands for Numerical Python, is a library that provides a powerful and efficient way to work with numerical data in Python. NumPy provides a core object called ndarray, which is a multidimensional array that can store homogeneous data of any shape and size. NumPy also provides a large collection of functions and methods that can operate on ndarrays and perform various mathematical operations, such as linear algebra, statistics, trigonometry, and more.

To use NumPy, we need to import it in our Python code. The convention is to import it as np, like this:



In [ ]:
# import numpy as np
import numpy as np




To create an ndarray, we can use the np.array function, which takes a sequence of elements, such as a list or a tuple, and returns an ndarray with the same elements. For example, to create a one-dimensional ndarray with three elements, we can write:



In [ ]:
# create a one-dimensional ndarray with three elements
a = np.array([1, 2, 3])
# print the ndarray
print(a)




This will print:

[1 2 3]

To create a multidimensional ndarray, we can use nested sequences, such as nested lists or tuples, and specify the shape of the ndarray. For example, to create a two-dimensional ndarray with two rows and three columns, we can write:



In [ ]:
# create a two-dimensional ndarray with two rows and three columns
b = np.array([[1, 2, 3], [4, 5, 6]])
# print the ndarray
print(b)




This will print:

[[1 2 3]
 [4 5 6]]

To access the elements of an ndarray, we can use indexing and slicing, just like we do with Python lists. For example, to access the first element of the one-dimensional ndarray a, we can write:



In [ ]:
# access the first element of the one-dimensional ndarray a
print(a[0])




This will print:

1

To access the element in the second row and third column of the two-dimensional ndarray b, we can write:



In [ ]:
# access the element in the second row and third column of the two-dimensional ndarray b
print(b[1, 2])




This will print:

6

To perform mathematical operations on ndarrays, we can use the built-in arithmetic operators, such as +, -, *, /, and **, or the corresponding NumPy functions, such as np.add, np.subtract, np.multiply, np.divide, and np.power. These operations are performed element-wise, meaning that they apply to each element of the ndarrays. For example, to add two ndarrays, we can write:



In [ ]:
# create two ndarrays
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])
# add the ndarrays
e = c + d
# print the result
print(e)




This will print:

[5 7 9]

To perform more advanced mathematical operations on ndarrays, such as matrix multiplication, dot product, inverse, determinant, and more, we can use the np.linalg module, which provides linear algebra functions. For example, to compute the dot product of two ndarrays, we can write:



In [ ]:
# create two ndarrays
f = np.array([1, 2, 3])
g = np.array([4, 5, 6])
# compute the dot product of the ndarrays
h = np.dot(f, g)
# print the result
print(h)




This will print:

32

NumPy also provides many functions and methods that can perform statistical operations on ndarrays, such as calculating the mean, median, standard deviation, variance, and more. For example, to calculate the mean of an ndarray, we can write:



In [ ]:
# create an ndarray
i = np.array([1, 2, 3, 4, 5])
# calculate the mean of the ndarray
j = np.mean(i)
# print the result
print(j)




This will print:

3.0

These are just some of the basic features and functionalities of NumPy. NumPy is a very powerful and versatile library that can handle a wide range of numerical data and computations. To learn more about NumPy, you can check out the official documentation¹ or some of the online tutorials²³.

## Pandas for Data Manipulation

Pandas, which stands for Panel Data Analysis, is a library that provides high-performance and easy-to-use data structures and tools for data manipulation and analysis in Python. Pandas is built on top of NumPy and integrates well with other libraries, such as Matplotlib, SciPy, and scikit-learn. Pandas is widely used for data science, machine learning, and data visualization projects.

The main data structure in Pandas is the DataFrame, which is a two-dimensional tabular data structure that can store heterogeneous data of different types and sizes. A DataFrame consists of rows and columns, where each column is a Series, which is a one-dimensional array-like object that can store a single type of data. A DataFrame can be created from various sources, such as lists, dictionaries, ndarrays, files, or databases.

To use Pandas, we need to import it in our Python code. The convention is to import it as pd, like this:



In [ ]:
# import pandas as pd
import pandas as pd




To create a DataFrame from a list of lists, we can use the pd.DataFrame function, which takes a list of lists as the data argument, and optionally, a list of strings as the columns argument, which specifies the names of the columns. For example, to create a DataFrame with three rows and two columns, we can write:



In [ ]:
# create a DataFrame from a list of lists
k = pd.DataFrame(data=[[1, 'Alice'], [2, 'Bob'], [3, 'Charlie']], columns=['ID', 'Name'])
# print the DataFrame
print(k)




This will print:

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

To create a DataFrame from a dictionary of lists, we can use the pd.DataFrame function, which takes a dictionary of lists as the data argument, where the keys are the names of the columns, and the values are the lists of data for each column. For example, to create a DataFrame with the same data as before, but using a dictionary of lists, we can write:



In [ ]:
# create a DataFrame from a dictionary of lists
l = pd.DataFrame(data={'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
# print the DataFrame
print(l)




This will print:

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

To create a DataFrame from a file, such as a CSV file, we can use the pd.read_csv function, which takes the file name or path as the first argument, and optionally, other arguments, such as sep, which specifies the delimiter, header, which specifies the row number of the header, index_col, which specifies the column number of the index, and more. For example, to create a DataFrame from a CSV file named data.csv, which has a comma as the delimiter, the first row as the header, and the first column as the index, we can write:



In [ ]:
# create a DataFrame from a CSV file
m = pd.read_csv('data.csv', sep=',', header=0, index_col=0)
# print the DataFrame
print(m)




This will print:

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

To access the elements of a DataFrame, we can use various methods, such as loc, iloc, and ix, which allow us to select rows and columns by labels, positions, or a combination of both. For example, to access the element in the second row and first column of the DataFrame k, we can write:



In [ ]:
# access the element in the second row and first column of the DataFrame k
print(k.loc[1, 'ID'])




To sort the DataFrame k by the Name column in ascending order, we can write:



In [ ]:
# sort the DataFrame k by the Name column in ascending order
n = k.sort_values(by='Name')
# print the sorted DataFrame
print(n)




This will print:

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie


In [ ]:

To filter the DataFrame k by the ID column, and select only the rows where the ID is greater than 1, we can write:



python
# filter the DataFrame k by the ID column
o = k[k['ID'] > 1]
# print the filtered DataFrame
print(o)


In [ ]:

This will print:

   ID     Name
1   2      Bob
2   3  Charlie




To group the DataFrame k by the Name column, and calculate the mean of the ID column for each group, we can write:



In [ ]:
# group the DataFrame k by the Name column
p = k.groupby('Name')
# calculate the mean of the ID column for each group
q = p['ID'].mean()
# print the result
print(q)




This will print:

Name
Alice      1
Bob        2
Charlie    3
Name: ID, dtype: int64


In [ ]:

To merge two DataFrames, such as k and l, by a common column, such as ID, we can use the pd.merge function, which takes the two DataFrames as the left and right arguments, and the name of the common column as the on argument. For example, to merge k and l by the ID column, we can write:



python
# merge k and l by the ID column
r = pd.merge(k, l, on='ID')
# print the merged DataFrame
print(r)


In [ ]:

This will print:

   ID   Name_x   Name_y
0   1    Alice    Alice
1   2      Bob      Bob
2   3  Charlie  Charlie



## Matplotlib for Data Visualization

Matplotlib is a library that provides a comprehensive and flexible way to create and customize plots and charts to display and explore data in Python. Matplotlib is built on top of NumPy and integrates well with other libraries, such as Pandas, SciPy, and scikit-learn. Matplotlib is widely used for data science, machine learning, and data visualization projects.

The main object in Matplotlib is the figure, which is a container that holds one or more axes, which are the actual plots or charts that display the data. A figure can have multiple axes, which can have different types, such as line plots, scatter plots, bar charts, pie charts, histograms, and more. A figure can also have other elements, such as titles, labels, legends, grids, and annotations.

To use Matplotlib, we need to import it in our Python code. The convention is to import it as plt, like this:



In [ ]:
# import matplotlib as plt
import matplotlib.pyplot as plt




To create a figure and an axis, we can use the plt.subplots function, which returns a figure object and an axis object. For example, to create a figure with one axis, we can write:



In [ ]:
# create a figure with one axis
fig, ax = plt.subplots()




To create a plot or a chart on the axis, we can use one of the methods of the axis object, such as plot, scatter, bar, pie, hist, and more. These methods take the data to be plotted as arguments, and optionally, other arguments, such as color, marker, linestyle, label, and more. For example, to create a line plot on the axis with some sample data, we can write:



In [ ]:
# create some sample data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
# create a line plot on the axis
ax.plot(x, y, color='red', marker='o', label='Line')




To add other elements to the figure, such as titles, labels, legends, grids, and annotations, we can use the methods of the figure object, the axis object, or the plt module. For example, to add a title to the figure, a label to the x-axis, a legend to the plot, and a grid to the axis, we can write:



In [ ]:
# add a title to the figure
fig.suptitle('Sample Figure')
# add a label to the x-axis
ax.set_xlabel('X')
# add a legend to the plot
ax.legend()
# add a grid to the axis
ax.grid()




To show the figure on the screen, we can use the plt.show function, which displays the figure in a new window. For example, to show the figure that we created, we can write:



In [ ]:
# show the figure on the screen
plt.show()
